### ISSUE TITLE
Fork vs. FOR

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/css_above_the_fold#3]
Dieses Repo ist aktuell ein Fork und passt damit nicht so recht zu FOR. Wie sind denn die weiteren Pläne, soll es mal ein richtiges FOR-Projekt werden, oder geht es nur darum, dem Autor PRs zukommen zu lassen?

Wenn es ein FOR-Projekt werden soll, muss dies natürlich vom ursprünglichen Autor gewollt sein. Dann würde man das Repo an FOR übertragen, siehe https://friendsofredaxo.github.io/info#ein-addon-zu-den-friends-of-redaxo-übertragen.

Wenn es hingegen nur um PRs geht, sollte ein Projekt besser nicht von FOR geforkt werden, sondern von einem separaten GitHub-Account.

**Comment by AWqxKAWERbXo** [comment]
War vlt. ein Versehen vom Forker?

**Comment by schuer** [comment]
@lexplatt, du hast es geforkt, oder? Kannst du was dazu sagen?

**Comment by lexplatt** [comment]
ja ich habe mich mit Adrian in Verbindung gesetzt und er hat sein OK gegeben und wollte mir seine Repo übertragen, damit ichs auf FOR veröffentliche. Es ging ihm damals zeitlich aber nicht aus und dann ists wieder versandet... ich werde ihn nochmals kontaktieren

**Comment by schuer** [comment]
@akuehnis, magst du das Projekt noch FOR übertragen? https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io#ein-addon-zu-den-friends-of-redaxo-übertragen
FOR würde sich freuen :)

Falls nein, kein Problem, aber dann sollten wir dieses Repo zum @lexplatt rüberschieben.

**Comment by schuer** [comment]
Ping! Jemand da? :)

**Comment by akuehnis** [comment]
Ja, da. Keine Zeit. Sorry.

**Comment by schuer** [comment]
Ich hatte den GitHub-Support gebeten, _unseren_ Fork vom Hauptprojekt zu kappen, damit wir hier in Ruhe weiterarbeiten können.
